#ifndef MOFGBMLPY_CORE_FUZZY_TERM_FUZZY_SET_DIVISION_TYPE_HPP
#define MOFGBMLPY_CORE_FUZZY_TERM_FUZZY_SET_DIVISION_TYPE_HPP

enum DivisionType {
    EQUAL_DIVISION = 0,
    ENTROPY_DIVISION = 1
};

#endif // MOFGBMLPY_CORE_FUZZY_TERM_FUZZY_SET_DIVISION_TYPE_HPP

